### ISSUE TITLE
Problems using this Module

### ISSUE THREAD

**Issue by mindrunner** [danbohea/ansible-role-rbenv#1]
Hi, I am seeing alot of problems while trying to use this.

```
21:44:23 ok: [wzumacmini4-2] => {
21:44:23     "changed": false, 
21:44:23     "cmd": [
21:44:23         "whereis", 
21:44:23         "-b", 
21:44:23         "rvm"
21:44:23     ], 
21:44:23     "delta": "0:00:00.010971", 
21:44:23     "end": "2017-03-26 12:44:23.502196", 
21:44:23     "failed": false, 
21:44:23     "failed_when_result": false, 
21:44:23     "rc": 1, 
21:44:23     "start": "2017-03-26 12:44:23.491225", 
21:44:23     "warnings": []
21:44:23 }
21:44:23 
21:44:23 STDERR:
21:44:23 
21:44:23 whereis: illegal option -- b
21:44:23 usage: whereis program [...]
21:44:23 
```

```
21:44:47 fatal: [wzumacmini4-2]: FAILED! => {
21:44:47     "changed": true, 
21:44:47     "cmd": "eval \"$(rbenv init -)\"; rbenv install 2.1.2", 
21:44:47     "delta": "0:00:00.020316", 
21:44:47     "end": "2017-03-26 12:44:46.980065", 
21:44:47     "failed": true, 
21:44:47     "rc": 127, 
21:44:47     "start": "2017-03-26 12:44:46.959749", 
21:44:47     "warnings": []
21:44:47 }
21:44:47 
21:44:47 STDERR:
21:44:47 
21:44:47 /bin/sh: rbenv: command not found
21:44:47 /bin/sh: rbenv: command not found
21:44:47 
```

I am running ansilble with this playbook:

```
---
- hosts: all
  roles:
    - role: danbohea.rbenv
```

Anything, i am overlooking here?

**Comment by dixhuit** [comment]
~~Aaah, yes that may be because you haven't updated your .bash_profile as rbenv requires. I do this separately via my dotfiles like this:~~ ~~https://github.com/danbohea/dotfiles/blob/master/.bash_profile#L26-L30~~

~~I didn't want to presume to amend people's .bash_profile via this Ansible role but you raise a good point, maybe it should at least test for this and provide better feedback if it fails. I'll also make a note to update the readme. Please let me know if this fixes things for you :)~~

**Comment by dixhuit** [comment]
Scratch that, read your comment too quickly while doing something else :) Can you share some details about the system your attempting this on? OS version etc? Automated tests should cover this but maybe I've missed something.

**Comment by mindrunner** [comment]
Thanks for answering. I already figured out that (probably) your module is made for local provisioning. I am doing remote provisioning on vagrant virtual machines. Thus, I need to setup the environment for non-login shell usage. Maybe you should state that in your documentation. (.bash_profile / .bashrc) is a good hint, though.
Anyway, I solved my problem and it is working (alsmost) flawlessly.

still, `whereis -b rvm` should be `whereis rvm`
at least in most recent macOS

**Comment by dixhuit** [comment]
Yes, this role was originally intended for local provisioning. I'll make a note to update the README.

`whereis -b rvm` seems to work fine on the 3 versions of macOS I test against: https://travis-ci.org/danbohea/ansible-role-rbenv

**Comment by mindrunner** [comment]
I cannot see what versions of macOS you are testing with. Furthermore I think, you should run ansible with `-vvv` parameter to see actual console output. It is not clear, whether the command fails or not, because any "fail" exit code is considered as good in your recipe, isnt it?

**Comment by dixhuit** [comment]
From the readme: "macOS 10.10, 10.11 or 10.12". These map to the 3 build jobs you see in the linked Travis report. I'd like to make it clearer but that's a restriction of Travis itself which assumes I'm more interested in the Xcode version than the macOS version.

> any "fail" exit code is considered as good in your recipe, isnt it?

Not quite. The task your referring to is set to never report as _changed_, it still respects a fail exit code.

**Comment by mindrunner** [comment]
How about testing your code on a system where rvm is installed. What result would you expect? Did you ever test it?

**Comment by dixhuit** [comment]
That's precisely what the Travis tests do so yes, that is tested every time I push changes to the GitHub repo (and every time someone submits a PR, just like the you did).

https://docs.travis-ci.com/user/osx-ci-environment/#Ruby-versions-implementations
